---
name: Main

on:
  pull_request:
    paths-ignore:
      - '**.md'

  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: Build
    runs-on: windows-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal