---
name: Morphology

on:
  pull_request:
    paths-ignore:
      - '**.md'

  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: Build
    runs-on: windows-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Restore dependencies
        run: dotnet restore
      - name: Build Morphology
        run: dotnet build ${{ github.workspace }}/src/MorphologyTask/Morphology/Morphology.csproj --no-restore
      - name: Test Morphology
        run: dotnet test ${{ github.workspace }}/src/MorphologyTask/Morphology.Tests/Morphology.Tests.csproj --no-restore --verbosity normal